torso_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - torso_lift_joint

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0 # FIXME: See #8429
    torso_lift_joint:
      goal: 0.02


head_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - head_1_joint
    - head_2_joint

  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 5.0
    head_1_joint:
      goal: 0.5
    head_2_joint:
      goal: 0.5

arm_left_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0
    arm_left_1_joint:
      goal: 0.025
    arm_left_2_joint:
      goal: 0.025
    arm_left_3_joint:
      goal: 0.025
    arm_left_4_joint:
      goal: 0.025
    arm_left_5_joint:
      goal: 0.025
    arm_left_6_joint:
      goal: 0.025
    arm_left_7_joint:
      goal: 0.025

arm_right_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0
    arm_right_1_joint:
      goal: 0.025
    arm_right_2_joint:
      goal: 0.025
    arm_right_3_joint:
      goal: 0.025
    arm_right_4_joint:
      goal: 0.025
    arm_right_5_joint:
      goal: 0.025
    arm_right_6_joint:
      goal: 0.025
    arm_right_7_joint:
      goal: 0.025
